---
title: "Olten Vitaparcours STRAVA 2"
format: 
  html: default
  typst: 
    toc: true
author: Rodrigo Nogueira Silva
execute: 
  warning: false
  message: false
  echo: false
---


##Vitaparcours Olten 2

```{r}
library("readr")

Vita2 <- read_delim("datasets/Vita_2/track_points.csv", ",")



library(sf)

Vita_sf2 <- st_as_sf(
  Vita2,
  coords = c("X", "Y"),
  crs = 2056, remove = FALSE)

library(ggplot2)

ggplot(Vita_sf2)+
  geom_sf()+
  geom_path(aes(X,Y))
  

```



```{r}

library(dplyr)
distance_by_element2 <- function(later, now) {
  as.numeric(
    st_distance(later, now, by_element = TRUE)
  )
}


route2 <- Vita_sf2 |>
    mutate(
        nMinus2 = distance_by_element2(lag(geometry, 2), geometry), 
        nMinus1 = distance_by_element2(lag(geometry, 1), geometry), 
        nPlus1  = distance_by_element2(geometry, lead(geometry, 1)), 
        nPlus2  = distance_by_element2(geometry, lead(geometry, 2)))



route2 <- route2 |>
    rowwise() |>
    mutate(
        stepMean2 = mean(c(nMinus2, nMinus1, nPlus1, nPlus2), na.rm = FALSE)
    ) |>
    ungroup()

```




```{r}

threshold2 <- mean(route2$stepMean2, na.rm = TRUE)


route2 <- route2 |>
    mutate(move2 = stepMean2 > threshold2)


ggplot(route2)+
  geom_sf(aes(color=move2))


route_static2 <- route2 |>
    filter(!move2)

ggplot(route_static2)+
  geom_sf(aes(color=move2))

```



```{r}
rle_id2 <- function(vec) {
    x <- rle(vec)$lengths
    as.factor(rep(seq_along(x), times = x))
}

route_id2 <- route2 |>
    mutate(segment_id2 = rle_id2(move2))

```



```{r}


library(tmap)
tmap_mode("view")

tm_shape(route_static2) + 
  tm_dots()

tmap_options(basemap.server = "OpenStreetMap")



```
