---
title: "Segmentation_function"
format: html
---

```{r}
library(sf)
library(dplyr)
library(purrr)
library(slider)
library(ggplot2)
library(patchwork)
library(igraph)

```


```{r}
# loading the cleand data with static events with different time windows (from preprocessing file)

# 10 Seconds Window
Strava_1_processed_10    <- st_read("datasets/cleaned/static/Strava_1_processed_10.gpkg", quiet = TRUE)
Strava_2_processed_10    <- st_read("datasets/cleaned/static/Strava_2_processed_10.gpkg", quiet = TRUE)
Swisstopo_1_processed_10 <- st_read("datasets/cleaned/static/Swisstopo_1_processed_10.gpkg", quiet = TRUE)
Swisstopo_2_processed_10 <- st_read("datasets/cleaned/static/Swisstopo_2_processed_10.gpkg", quiet = TRUE)
Posmo_1_processed_10     <- st_read("datasets/cleaned/static/Posmo_1_processed_10.gpkg", quiet = TRUE)
Posmo_2_processed_10     <- st_read("datasets/cleaned/static/Posmo_2_processed_10.gpkg", quiet = TRUE)

# 20 Seconds Window
Strava_1_processed_20    <- st_read("datasets/cleaned/static/Strava_1_processed_20.gpkg", quiet = TRUE)
Strava_2_processed_20    <- st_read("datasets/cleaned/static/Strava_2_processed_20.gpkg", quiet = TRUE)
Swisstopo_1_processed_20 <- st_read("datasets/cleaned/static/Swisstopo_1_processed_20.gpkg", quiet = TRUE)
Swisstopo_2_processed_20 <- st_read("datasets/cleaned/static/Swisstopo_2_processed_20.gpkg", quiet = TRUE)
Posmo_1_processed_20     <- st_read("datasets/cleaned/static/Posmo_1_processed_20.gpkg", quiet = TRUE)
Posmo_2_processed_20     <- st_read("datasets/cleaned/static/Posmo_2_processed_20.gpkg", quiet = TRUE)

# 30 Seconds Window
Strava_1_processed_30    <- st_read("datasets/cleaned/static/Strava_1_processed_30.gpkg", quiet = TRUE)
Strava_2_processed_30    <- st_read("datasets/cleaned/static/Strava_2_processed_30.gpkg", quiet = TRUE)
Swisstopo_1_processed_30 <- st_read("datasets/cleaned/static/Swisstopo_1_processed_30.gpkg", quiet = TRUE)
Swisstopo_2_processed_30 <- st_read("datasets/cleaned/static/Swisstopo_2_processed_30.gpkg", quiet = TRUE)
Posmo_1_processed_30     <- st_read("datasets/cleaned/static/Posmo_1_processed_30.gpkg", quiet = TRUE)
Posmo_2_processed_30     <- st_read("datasets/cleaned/static/Posmo_2_processed_30.gpkg", quiet = TRUE)

# 40 Seconds Window
Strava_1_processed_40    <- st_read("datasets/cleaned/static/Strava_1_processed_40.gpkg", quiet = TRUE)
Strava_2_processed_40    <- st_read("datasets/cleaned/static/Strava_2_processed_40.gpkg", quiet = TRUE)
Swisstopo_1_processed_40 <- st_read("datasets/cleaned/static/Swisstopo_1_processed_40.gpkg", quiet = TRUE)
Swisstopo_2_processed_40 <- st_read("datasets/cleaned/static/Swisstopo_2_processed_40.gpkg", quiet = TRUE)
Posmo_1_processed_40     <- st_read("datasets/cleaned/static/Posmo_1_processed_40.gpkg", quiet = TRUE)
Posmo_2_processed_40     <- st_read("datasets/cleaned/static/Posmo_2_processed_40.gpkg", quiet = TRUE)

# way points cleaned

wp_olten_clean    <- st_read("datasets/cleaned/Waypoints_Olten.gpkg", quiet = TRUE)
wp_wollerau_clean <- st_read("datasets/cleaned/Waypoints_Wollerau.gpkg", quiet = TRUE)

```


```{r}
# Plot the static events

theme_x_cord <- list(
  coord_sf(datum = 2056),
  theme_minimal(),
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 0.5),
    plot.title = element_text(size = 10, face = "bold")
  )
)

p1 <- ggplot(Strava_1_processed_10 ) +
  geom_sf(aes(color = is_static), size = 1) +
  scale_color_manual(values = c("TRUE" = "green", "FALSE" = "darkblue")) +
  labs(title = "Strava 1") +
  theme_x_cord

p2 <- ggplot(Strava_2_processed_10) +
  geom_sf(aes(color = is_static), size = 1) +
  scale_color_manual(values = c("TRUE" = "green", "FALSE" = "darkblue")) +
  labs(title = "Strava 2") +
  theme_x_cord

p3 <- ggplot(Swisstopo_1_processed_10) +
  geom_sf(aes(color = is_static), size = 1) +
  scale_color_manual(values = c("TRUE" = "green", "FALSE" = "darkblue")) +
  coord_sf(datum = 2056) +
  labs(title = "Swisstopo 1") +
  theme_x_cord

p4 <- ggplot(Swisstopo_2_processed_10) +
  geom_sf(aes(color = is_static), size = 1) +
  scale_color_manual(values = c("TRUE" = "green", "FALSE" = "darkblue")) +
  coord_sf(datum = 2056) +
  labs(title = "Swisstopo 2") +
  theme_x_cord

p5 <- ggplot(Posmo_1_processed_10) +
  geom_sf(aes(color = is_static), size = 1) +
  scale_color_manual(values = c("TRUE" = "green", "FALSE" = "darkblue")) +
  coord_sf(datum = 2056) +
  labs(title = "Posmo 1") +
  theme_x_cord

p6 <- ggplot(Posmo_2_processed_10) +
  geom_sf(aes(color = is_static), size = 1) +
  scale_color_manual(values = c("TRUE" = "green", "FALSE" = "darkblue")) +
  coord_sf(datum = 2056) +
  labs(title = "Posmo 2") +
  theme_x_cord

# creates a grid layout with 3 columns, and collects the legends into one clean spot
(p1 + p2 + p3) / (p4 + p5 + p6) + 
  plot_layout(guides = "collect") +
  plot_annotation(
    title = "Static vs. Moving",
    subtitle = "Time window of 10 seconds",
    theme = theme(plot.title = element_text(face = "bold", size = 14))
  )
```


```{r}

# clusters together points which are close together and compare them to the way point buffer

stops <- function(full_df, waypoints, max_dist_list, wp_buffer_list) {
  
  # only take static points
  static_only <- full_df |> 
    filter(is_static == TRUE)
  
  # Checks if there are no static points
  if (nrow(static_only) == 0) {
    return(st_as_sf(data.frame(geometry = st_sfc(), crs = st_crs(waypoints))))
  }
  
    all_results_list <- list()
  
  # cluster for each maximale distanz 
  for (md in max_dist_list) {
    
    # calculates distance matrix for all points
    # distance and adjacency matrix for the current max_dist (md)
    dist_matrix <- st_distance(static_only)
    adj_matrix <- dist_matrix <= units::set_units(md, "m")
    
    # give Cluster-IDs 
    g <- igraph::graph_from_adjacency_matrix(adj_matrix, mode = "undirected")
    static_only$cluster_id <- igraph::components(g)$membership
    
    # calculate centroids for specific max_dist
    current_centroids <- static_only |>
      group_by(cluster_id) |>
      summarise(.groups = "drop") |>
      st_centroid() |>
      mutate(max_dist_setting = md) # saves maximum distance at which this centroid was calculated
    
    # inner loop: For each buffer size around the waypoints
    for (buf_size in wp_buffer_list) {
      
      # calculate temporary buffer for the waypoints
      temp_buffer_df <- waypoints |>
        mutate(gt_id = row_number()) |>
        st_buffer(buf_size)
      
      intersect_list <- st_intersects(current_centroids, temp_buffer_df)
      
      # generate dynamic column names (e.g. in_buf_md10_b15)
      col_name_bool <- paste0("in_buf_md", md, "_b", buf_size)
      col_name_id   <- paste0("gt_id_md", md, "_b", buf_size)
      
      # Write the results as new columns in the temporary Centroid table
      current_centroids <- current_centroids |>
        mutate(
          !!col_name_bool := lengths(intersect_list) > 0,
          !!col_name_id   := sapply(intersect_list, function(x) if(length(x) > 0) temp_buffer_df$gt_id[x[1]] else NA)
        )
    }
    
    # Save the interim result for this max_dist in our list.
    all_results_list[[as.character(md)]] <- current_centroids
  }
  
  # Combine all the partial results (for each max_dist) into one large table.
  final_df <- bind_rows(all_results_list)
  
  return(final_df)
}

# buffer size around way points
max_dist_liste <- c(5, 10, 15)
wp_buffer_liste <- c(5, 10, 15)

# add stops to 10 second windows

Strava_1_10_stops_list <- stops(Strava_1_processed_10, wp_olten_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Strava_2_10_stops_list <- stops(Strava_2_processed_10, wp_olten_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Swisstopo_1_10_stops_list <- stops(Swisstopo_1_processed_10, wp_wollerau_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Swisstopo_2_10_stops_list <- stops(Swisstopo_2_processed_10, wp_wollerau_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Posmo_1_10_stops_list <- stops(Posmo_1_processed_10, wp_wollerau_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Posmo_2_10_stops_list <- stops(Posmo_2_processed_10, wp_wollerau_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)

# add stops to 20 second windows

Strava_1_20_stops_list <- stops(Strava_1_processed_20, wp_olten_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Strava_2_20_stops_list <- stops(Strava_2_processed_20, wp_olten_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Swisstopo_1_20_stops_list <- stops(Swisstopo_1_processed_20, wp_wollerau_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Swisstopo_2_20_stops_list <- stops(Swisstopo_2_processed_20, wp_wollerau_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Posmo_1_20_stops_list <- stops(Posmo_1_processed_20, wp_wollerau_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Posmo_2_20_stops_list <- stops(Posmo_2_processed_20, wp_wollerau_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)

# add stops to 30 second windows

Strava_1_30_stops_list <- stops(Strava_1_processed_30, wp_olten_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Strava_2_30_stops_list <- stops(Strava_2_processed_30, wp_olten_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Swisstopo_1_30_stops_list <- stops(Swisstopo_1_processed_30, wp_wollerau_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Swisstopo_2_30_stops_list <- stops(Swisstopo_2_processed_30, wp_wollerau_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Posmo_1_30_stops_list <- stops(Posmo_1_processed_30, wp_wollerau_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Posmo_2_30_stops_list <- stops(Posmo_2_processed_30, wp_wollerau_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)

# add stops to 30 second windows

Strava_1_40_stops_list <- stops(Strava_1_processed_40, wp_olten_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Strava_2_40_stops_list <- stops(Strava_2_processed_40, wp_olten_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Swisstopo_1_40_stops_list <- stops(Swisstopo_1_processed_40, wp_wollerau_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Swisstopo_2_40_stops_list <- stops(Swisstopo_2_processed_40, wp_wollerau_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Posmo_1_40_stops_list <- stops(Posmo_1_processed_40, wp_wollerau_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)
Posmo_2_40_stops_list <- stops(Posmo_2_processed_40, wp_wollerau_clean, max_dist = max_dist_liste, wp_buffer = wp_buffer_liste)

```



```{r}

# plot the combinations of clustering and buffering around waypoint

theme_x_cord <- list(
  coord_sf(datum = 2056),
  theme_minimal(),
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 0.5),
    plot.title = element_text(size = 9, face = "bold"),
    axis.title = element_blank()
  )
)

plot_liste <- list()

for (md in max_dist_liste) {
  
  strava_filtered <- Strava_1_stops_list |> 
    filter(max_dist_setting == md)
  
  for (buf in wp_buffer_liste) {
    
    current_col <- paste0("in_buf_md", md, "_b", buf)
    
    p <- ggplot() +
      geom_sf(data = st_buffer(wp_olten_clean, buf), fill = "gray70", alpha = 0.50, color = NA) +
      geom_sf(data = strava_filtered, aes(color = .data[[current_col]]), size = 1) +
      scale_color_manual(values = c("TRUE" = "green", "FALSE" = "blue")) +
      labs(title = paste0("MD: ", md, "m | Buffer: ", buf, "m"), color = "Inside?") +
      theme_x_cord
    
    plot_liste[[paste0("md", md, "_b", buf)]] <- p
  }
}

wrap_plots(plot_liste, ncol = 3) + 
  plot_layout(guides = "collect") + 
  plot_annotation(
    title = "Strava 1 - 9 combinations of clustering and buffering around waypoint",
    subtitle = "Cluster-Distanz (MD) | Waypoint-Buffer (Buffer)"
  )
```



